version: '3.6'


services:

  database:
    image: postgres:10.5
    container_name: database
    hostname: database
    restart: always 
    user: postgres
    
    ports: 
      - "5432:5432"
    networks:
      - db-tier
    volumes:
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  musicapp:
    image: python/music_app:0.1.0
    container_name: musicapp
    hostname: musicapp
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - app-tier
      - db-tier
    stdin_open: true

  nginx:
    image: nginx:1.22
    container_name: nginx-reverse-proxy-flask
    ports:
      - "8080:80"
    depends_on:
      - musicapp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge
  db-tier:
    driver: bridge
