version: '3.1'


services:

  database:
    image: postgres:9.6.24-alpine
    container_name: database
    restart: always 
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    networks:
      - app-tier
    volumes:
      - ./postgres/sql:/docker-entrypoint-initdb.d

  music-app:
    image: python/music_app:0.1.0
    container_name: musicapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - database
    networks:
      - app-tier
    stdin_open: true


networks:
  app-tier:
    driver: bridge
