apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-claim
  namespace: music-api
  labels:
    name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage