apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster
  namespace: music-api
  labels:
    name: postgres
spec:
  selector:
    name: postgres
  ports:
    - port: 5432
      targetport: 5432
